const colors = {
  light: {
    text: "#FFFFFF",
    tint: "#FF0080",
    background: "#0A0A0F",
    foreground: "#FFFFFF",
    card: "#111118",
    cardForeground: "#FFFFFF",
    primary: "#FF0080",
    primaryForeground: "#FFFFFF",
    secondary: "#1A1A26",
    secondaryForeground: "#FFFFFF",
    muted: "#1A1A26",
    mutedForeground: "#8A8A9A",
    accent: "#FF0080",
    accentForeground: "#FFFFFF",
    destructive: "#FF3B5C",
    destructiveForeground: "#FFFFFF",
    border: "#252535",
    input: "#1A1A26",
    surface: "#1A1A26",
    tabBar: "#0D0D15",
    success: "#00D68F",
    warning: "#FFB300",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#FF0080",
    background: "#0A0A0F",
    foreground: "#FFFFFF",
    card: "#111118",
    cardForeground: "#FFFFFF",
    primary: "#FF0080",
    primaryForeground: "#FFFFFF",
    secondary: "#1A1A26",
    secondaryForeground: "#FFFFFF",
    muted: "#1A1A26",
    mutedForeground: "#8A8A9A",
    accent: "#FF0080",
    accentForeground: "#FFFFFF",
    destructive: "#FF3B5C",
    destructiveForeground: "#FFFFFF",
    border: "#252535",
    input: "#1A1A26",
    surface: "#1A1A26",
    tabBar: "#0D0D15",
    success: "#00D68F",
    warning: "#FFB300",
  },
  radius: 12,
};

export default colors;
