import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import jadeRouter from "./jade.js";
import placesRouter from "./places.js";
import authRouter from "./auth.js";
import modulesRouter from "./modules.js";
import analyticsRouter from "./analytics.js";
import marketingRouter from "./marketing.js";
import activityRouter from "./activity.js";
import empresaRouter from "./empresa.js";
import relatoriosRouter from "./relatorios.js";
import timeRouter from "./time.js";
import carteiraRouter from "./carteira.js";
import metasRouter from "./metas.js";
import feedbackRouter from "./feedback.js";
import dashboardRouter from "./dashboard.js";
import planejamentoRouter from "./planejamento.js";
import notificacoesRouter from "./notificacoes.js";
import stripeRouter from "./stripe.js";
import whatsappRouter from "./whatsapp.js";
import adminRouter from "./admin.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/jade", jadeRouter);
router.use("/places", placesRouter);
router.use("/modules", modulesRouter);
router.use("/analytics", analyticsRouter);
router.use("/marketing", marketingRouter);
router.use("/activity", activityRouter);
router.use("/empresa", empresaRouter);
router.use("/relatorios", relatoriosRouter);
router.use("/time", timeRouter);
router.use("/carteira", carteiraRouter);
router.use("/metas", metasRouter);
router.use("/feedback", feedbackRouter);
router.use("/dashboard", dashboardRouter);
router.use("/planejamento", planejamentoRouter);
router.use("/notificacoes", notificacoesRouter);
router.use("/stripe", stripeRouter);
router.use("/whatsapp", whatsappRouter);
router.use("/admin", adminRouter);

export default router;
